#!/bin/bash

#SBATCH --job-name=create_env
#SBATCH --output=slurm_output/%x_%A.out
#also usable: --error
#SBATCH --time=00:08:00
#SBATCH --partition=staging
#SBATCH --nodes=1
#SBATCH --gpus=0
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1

module purge
module load 2022
module load Anaconda3/2022.05
module load Python/3.10.4-GCCcore-11.3.0

cd $HOME/Misinformation-Detection-in-LLMs/
conda env create -f environment.yml
